//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentManagementSystem.Resources.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courses_get.
        /// </summary>
        public static string Courses_Get {
            get {
                return ResourceManager.GetString("Courses_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courses_insert.
        /// </summary>
        public static string Courses_Insert {
            get {
                return ResourceManager.GetString("Courses_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courses_list.
        /// </summary>
        public static string Courses_List {
            get {
                return ResourceManager.GetString("Courses_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courses_update.
        /// </summary>
        public static string Courses_Update {
            get {
                return ResourceManager.GetString("Courses_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daysOfWeek_list.
        /// </summary>
        public static string DaysOfWeek_List {
            get {
                return ResourceManager.GetString("DaysOfWeek_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departments_list.
        /// </summary>
        public static string Departments_List {
            get {
                return ResourceManager.GetString("Departments_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructorcourseassoc_delete.
        /// </summary>
        public static string InstructorCourseAssoc_Delete {
            get {
                return ResourceManager.GetString("InstructorCourseAssoc_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructorcourseassoc_get.
        /// </summary>
        public static string InstructorCourseAssoc_Get {
            get {
                return ResourceManager.GetString("InstructorCourseAssoc_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructorcourseassoc_insert.
        /// </summary>
        public static string InstructorCourseAssoc_Insert {
            get {
                return ResourceManager.GetString("InstructorCourseAssoc_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructorcourseassoc_list.
        /// </summary>
        public static string InstructorCourseAssoc_List {
            get {
                return ResourceManager.GetString("InstructorCourseAssoc_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructorcourseassoc_update.
        /// </summary>
        public static string InstructorCourseAssoc_Update {
            get {
                return ResourceManager.GetString("InstructorCourseAssoc_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles_list.
        /// </summary>
        public static string Roles_List {
            get {
                return ResourceManager.GetString("Roles_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semesters_list.
        /// </summary>
        public static string Semesters_List {
            get {
                return ResourceManager.GetString("Semesters_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to studentcourseassoc_delete.
        /// </summary>
        public static string StudentCourseAssoc_Delete {
            get {
                return ResourceManager.GetString("StudentCourseAssoc_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to studentcourseassoc_get.
        /// </summary>
        public static string StudentCourseAssoc_Get {
            get {
                return ResourceManager.GetString("StudentCourseAssoc_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to studentcourseassoc_insert.
        /// </summary>
        public static string StudentCourseAssoc_Insert {
            get {
                return ResourceManager.GetString("StudentCourseAssoc_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to studentcourseassoc_list.
        /// </summary>
        public static string StudentCourseAssoc_List {
            get {
                return ResourceManager.GetString("StudentCourseAssoc_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users_delete.
        /// </summary>
        public static string Users_Delete {
            get {
                return ResourceManager.GetString("Users_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users_get.
        /// </summary>
        public static string Users_Get {
            get {
                return ResourceManager.GetString("Users_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users_insert.
        /// </summary>
        public static string Users_Insert {
            get {
                return ResourceManager.GetString("Users_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users_list.
        /// </summary>
        public static string Users_List {
            get {
                return ResourceManager.GetString("Users_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users_update.
        /// </summary>
        public static string Users_Update {
            get {
                return ResourceManager.GetString("Users_Update", resourceCulture);
            }
        }
    }
}
